### ISSUE TITLE
Checkout Error

### ISSUE THREAD

**Issue by rylanharper** [thetre97/gridsome-starter-shopify-account#1]
Hi there! 👋 THIS is the template I have been waiting forever for! I cannot thank you enough for your work on this!!

Small (not-so-small) bug/error when navigating back to the site from the checkout page.. Seems the pages/images do not load in due to a cache error. Its even worse when logged into a user account and doesn't allow me to navigate the site at all 🙃

To recreate this add a product to the cart then checkout > domain.myshopify.com > then navigate back to site. I get this:

![Capture](https://user-images.githubusercontent.com/16216160/86855055-7b8d1300-c06e-11ea-8a2a-80d1e6909b6b.PNG)

**Comment by travis-r6s** [comment]
@rylanharper You're welcome 🙂 

Yeh, I noticed that too. Turns out service workers are hard 🙄I pushed an update that remove caching for the JS, and it seems to have fixed it, at least on my preview. Try changing the sw config to this (or removing completely):

```js
{
  use: 'gridsome-plugin-service-worker',
  options: {
    staleWhileRevalidate: {
      cacheName: 'static-resources',
      routes: [/\.(?:css)$/]
    }
  }
}
```

**Comment by rylanharper** [comment]
Yeah service workers are insane lol 👀 Okay cool that fix seems to be working on my dev environment and images and pages are coming back in. I have a couple more questions regarding how to go about testing the user accounts while in a dev environment.. I may open another ticket for that
